server:
  port: 9090

zipkin:
  base-url: http://localhost:9411
  enable: true
sleuth:
  sampler:
    probability: 1.0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instances:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/car/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/api/bike/**
