server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/AntonioYances/microservices-config/tree/main/src/main/resources


application:
  name: config-server

